services:
  nginx:
    image: nginx:1.27-alpine
    container_name: fraud-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - fraud-net
    cpus: "0.10"
    mem_limit: 6m
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 6MB

  api1:
    image: ghcr.io/nrlacerda/fraud-detection-api:latest
    container_name: fraud-api1
    environment:
      INDEX_PATH: /hnsw.bin
      LISTEN_ADDR: :8080
      GOMAXPROCS: "2"
    expose:
      - "8080"
    networks:
      - fraud-net
    cpus: "0.45"
    mem_limit: 172m
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 172MB

  api2:
    image: ghcr.io/nrlacerda/fraud-detection-api:latest
    container_name: fraud-api2
    environment:
      INDEX_PATH: /hnsw.bin
      LISTEN_ADDR: :8080
      GOMAXPROCS: "2"
    expose:
      - "8080"
    networks:
      - fraud-net
    cpus: "0.45"
    mem_limit: 172m
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 172MB
    depends_on:
      - api1

networks:
  fraud-net:
    driver: bridge
